### ISSUE TITLE
Javascript syntax highlighting issue with vim-jsx and vim-javascript plugins on together

### ISSUE THREAD

**Issue by jltwheeler** [bluz71/vim-nightfly-guicolors#20]
Running:
- Iterm2 v3.4.5
- Neovim v0.4.4

I noticed that if I have both the `vim-javascript` and `vim-jsx` plugins defined in my `init.vim` file, I get some weird syntax highlighting issues on the `if` statement, parenthesis and the string passed into `console.log`. There could be more discrepancies, but this is the ones I picked up from a quick glance. Not sure if this is an issue with this theme or the actual plugins?

See below

```vimrc
" Snippet of init.vim config
...
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
...
```

1. With both `vim-javascript` and `vim-jsx` switched on in `init.vim`

![Screenshot 2021-05-24 at 23 01 49](https://user-images.githubusercontent.com/63519262/119412576-06591980-bce4-11eb-86ce-4afefc411475.png)

2. Only `vim-javascript` switched on in `init.vim`

![Screenshot 2021-05-24 at 23 07 14](https://user-images.githubusercontent.com/63519262/119413040-c8102a00-bce4-11eb-8dc0-ca94ccc075e1.png)

**Comment by bluz71** [comment]
This is the result I get (in Neovim 0.5) with these plugins enabled:

```viml
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
```

![Screenshot](https://user-images.githubusercontent.com/11382509/119435704-0b5aaf00-bd5e-11eb-8319-78640a97fb33.png)

If is correctly highlighted for me, same for the arrow function in green.

If I was to guess, maybe the linter you are running is effecting things, or maybe there is a weird interaction happening with another plugin (maybe vim-polyglot)? That will need some debugging from your side.

For now I think it is best to close this since there does not appear to be an issue with the color scheme.

Good luck finding the issue.
