### ISSUE TITLE
[TS] Unused variables are impossible to see 

### ISSUE THREAD

**Issue by pallymore** [bluz71/vim-nightfly-guicolors#31]
Hello - after recent updates I've noticed unused variables are almost impossible to see. I suspect it has something to do with this commit: https://github.com/bluz71/vim-nightfly-guicolors/commit/673d276970bfd0e8aad684a0a96543ad67574c7b 
which removes the white color for `CocUnusedHighlight` 

now in TS files unused variables look like this:

![CleanShot 2021-12-06 at 10 40 05](https://user-images.githubusercontent.com/2566530/144875886-434b488a-646b-46b8-8aa7-64f308037bf9.png)

I'm using nvim 0.6 (linux), `nvim-treesitter`, `nvim-lspconfig`, and `coc.nvim`

**Comment by bluz71** [comment]
Apologies, my bad.

I just committed a fix that should resolve this issue.

Best regards.

**Comment by pallymore** [comment]
awesome, thanks for the quick fix!

**Comment by bluz71** [comment]
Hello again,

I decided to explore this issue by installinf CoC and trying to recreate your issue.
Which I am not able to do.
I too am using Neovim 0.6 (linux) with treesitter and CoC (latest release branch version as of December 8).

By default `CocUnusedHighlight` links to `CocFadeOut` which itself links to `Conceal`.
Commit [`673d276`](https://github.com/bluz71/vim-nightfly-guicolors/commit/673d276970bfd0e8aad684a0a96543ad67574c7b) removed the `CocUnusedHighlight` group but also changed the color of `Conceal` to a lighter color.

My workaround for you really should not be needed, and from my testing it isn't needed. Hence, I will remove it. It will likely break your setup, but we should debug the underlying cause of your issue since I think the `CocUnusedHighlight` group is somehow screwed up in your setup.

In your case I suggest you run the following commands and see if they match my results:

![First](https://user-images.githubusercontent.com/11382509/145148069-192ffa6a-e581-489a-8191-43d82f5bb76d.png)

![Second](https://user-images.githubusercontent.com/11382509/145148079-8fad4bf8-9223-48ab-9739-9976c3169dc1.png)

![Third](https://user-images.githubusercontent.com/11382509/145148101-36587f49-051c-425d-88bb-fb04192a02f1.png)

If you don't have time to debug you could temporarily add the following to your setup to get you by:

```viml
hi link CocUnusedHighlight TSVariable
```

**Comment by pallymore** [comment]
Hi - thanks for the update. 

here're my results:

![CleanShot 2021-12-08 at 00 22 04](https://user-images.githubusercontent.com/2566530/145152872-441c2033-e431-4285-beb3-9027253f675c.png)

![CleanShot 2021-12-08 at 00 22 22](https://user-images.githubusercontent.com/2566530/145152896-741bf339-cbbe-4826-aa56-06cc5675b3dd.png)

![CleanShot 2021-12-08 at 00 22 34](https://user-images.githubusercontent.com/2566530/145152922-009c463e-3de8-469d-a9e7-625e9f2cefdc.png)

for some reason I have a different Conceal color 🤔

**Comment by pallymore** [comment]
OK I think i figured it out - this seems to have something to do with https://github.com/Yggdroot/indentLine 

I'm getting the same color as you did as soon as I remove `indentLine` - could you confirm if you could reproduce the issue with that plugin?

**Comment by bluz71** [comment]
Yeah, I can repeat it now.

indentLine plugin completely overwrites the value of `Conceal` unless you set:

```
let g:indentLine_setColors = 0
```

I don't encounter this issue since I use the [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) which is a **much better** plugin for use in Neovim. It uses virtual text for the indent guides instead of concealed text.

As for the combination of indentLine and CoC, let me think about things. I need to figure out a solution that works best for everyone. That may just be as simple as reverting my reverting.

Thanks for taking the time, I appreciate it.

**Comment by bluz71** [comment]
Sorry for the diversion :)

I have added the workaround back in.....and now I know about the issues of [indentLine](https://github.com/Yggdroot/indentLine); I can keep that in the memory bank if other users encounter `Conceal` issues. So this little exercise is still useful to me.

In your case, I strongly suggest moving over to [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) which is a much better plugin than indentLine; it is even treesitter aware. [Here is my indent-blankline config](https://github.com/bluz71/dotfiles/blob/master/vim/lua/plugin/indent-blankline.lua).

Cheers.

**Comment by pallymore** [comment]
Thank you! I will switch to `indent-blankline` instead 😬
