### ISSUE TITLE
Extremely hard to notice `listchars`

### ISSUE THREAD

**Issue by ibhagwan** [bluz71/vim-nightfly-guicolors#32]
First, ty for this fantastic colorscheme, love it :-)

As you can see below the current listchars highlights makes it extremley hard to notice some `listchars` (aside from the EOL):
> the right side of the screen is the embark colorscheme with transparent background:
![image](https://user-images.githubusercontent.com/59988195/173122680-bf1dfed4-dc73-48eb-8393-97a36b6c8a7a.png)

**Comment by bluz71** [comment]
Hello @ibhagwan,

I believe you use Neovim since you are the maintainer of *fzf-lua*.

The color of `listchars` is dictated by the `Whitespace` highlight group, in Neovim, which influences not only `listchars` but *indent-blankline*  indent markers and highlighting in the QuickFix list. So a very subtle color is a deliberate choice.

Though I can understand your issue; thankfully there is an easy solution, just change the color of `Whitespace` as follows (after setting `colorscheme`):

```viml
if g:colors_name == 'nightfly'
    highlight! link Whitespace NonText
endif
```

Add to the end of `init.vim` or in an after file such as `after/plugin/colorscheme.vim` (in your Neovim runtime path).

Cheers.

**Comment by ibhagwan** [comment]
Thank you for the prompt reply @bluz71!

> I believe you use Neovim since you are the maintainer of fzf-lua.

Correct.

> The color of `listchars` is dictated by the Whitespace highlight group, in Neovim, which influences not only `listchars` but indent-blankline indent markers and highlighting in the QuickFix list. So a very subtle color is a deliberate choice.

Makes sense, I didn’t know indent-blankline uses the same highlights, I recently started using to `mini-indentscope` from [mini.nvim](https://github.com/echasnovski/mini.nvim) (amazing library btw, the surround plugin is the best I’ve used and the indent scope text object is very useful).

> Though I can understand your issue; thankfully there is an easy solution, just change the color of Whitespace as follows (after setting `colorscheme`)

Thank you for the suggestion, will modify my config accordingly :)

**Comment by bluz71** [comment]
No problem.

I am pleased you like the colorscheme.
Keep up the good work you do in the open-source community.

Cheers.
