### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by thanh-vo-opun-ai** [bluz71/vim-nightfly-guicolors#36]
Hi, 
I encounter this error:
<img width="951" alt="Screen Shot 2022-10-04 at 11 25 43 AM" src="https://user-images.githubusercontent.com/75952754/193896754-bb16f7ad-05c5-4bf1-b532-0d5147c77fcb.png"> 

My neovim version is 0.8

**Comment by bluz71** [comment]
Are you using Neovim 0.8 or an older nightly? This looks like the Tressitter highlight group renames I did a couple weeks ago because the Neovim devs themselves changed group names.

Please provide the exact Neovim version you are using via the `:intro` command.

Note, I am a Neovim 0.8 user, so this theme does work, but it requires the official 0.8 release.

**Comment by thanh-vo-opun-ai** [comment]
@bluz71  my nvim version
> nvim --version
NVIM v0.8.0-dev+377-gae02c02f1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by thanh-vo-opun-ai** [comment]
my temporary solution is to use old commit
use({ "bluz71/vim-nightfly-guicolors", commit = "7a03fd3061f38643acc48e7976e8ecfe10692aa9" })

**Comment by bluz71** [comment]
As suspected, you are using an older development version of Neovim (a nightly).

Please upgrade to the official Neovim 0.8 release, it is required.

Best regards.

**Comment by bluz71** [comment]
> my temporary solution is to use old commit
> use({ "bluz71/vim-nightfly-guicolors", commit = "7a03fd3061f38643acc48e7976e8ecfe10692aa9" })

No, please upgrade your Neovim, that is the issue.

**Comment by thanh-vo-opun-ai** [comment]
Things works fine after upgrading Neovim
Thanks for your support

**Comment by bluz71** [comment]
Cheers.
